name: Windows Build

on:
  push:
    branches:
      - master
      - main
      - 'feature/**'
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Intel oneAPI MKL Headers (Windows)
        shell: bash
        run: |
          curl -L -s -o mkl_include.zip "https://files.pythonhosted.org/packages/48/2e/8c71366e2f35ba74704b68be65caec6674472e7913ead5196cc69a15001e/mkl_include-2026.1.0-py2.py3-none-win_amd64.whl"
          unzip -q mkl_include.zip -d mkl_tmp
          mkdir -p "C:/Program Files (x86)/Intel/oneAPI/mkl/latest/include"
          MKL_DIR=$(dirname $(find mkl_tmp -name "mkl.h" | head -n 1))
          cp -r "$MKL_DIR"/* "C:/Program Files (x86)/Intel/oneAPI/mkl/latest/include/"

      - name: Install Intel oneAPI MKL Static (Windows)
        shell: bash
        run: |
          curl -L -s -o mkl_static.zip "https://files.pythonhosted.org/packages/13/de/947be8379312d458a2c78c3895b3e70461db1c8e5bf0c8d37fba0e756f22/mkl_static-2026.1.0-py2.py3-none-win_amd64.whl"
          unzip -q mkl_static.zip -d mkl_static_tmp
          mkdir -p "C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/intel64"
          cp -r mkl_static_tmp/mkl_static-2026.1.0.data/data/Library/lib/* "C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/intel64/"

      - name: Install FFTW3 (Windows)
        run: vcpkg install fftw3:x64-windows

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DSAF_ENABLE_SOFA_READER_MODULE=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DINTEL_MKL_LIB="C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/intel64/mkl_intel_lp64.lib;C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/intel64/mkl_sequential.lib;C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/intel64/mkl_core.lib"
      - name: Build plugins
        run: cmake --build build --config Release --parallel 4 --target sparta_MCFX-6DoFconv_VST3

      - name: Upload VST3 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SPARTA-Windows-VST3
          path: build/audio_plugins/**/Release/VST3/*.vst3
          
      - name: Upload VST Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SPARTA-Windows-VST
          path: build/audio_plugins/**/Release/VST/*.dll
